version: "3.8"

services:
  # The Frontend Service
  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:80"
    depends_on:
      - backend-java

  # The Java Backend Service
  backend-java:
    build:
      context: ./backend-java
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5432/legal-tech
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    depends_on:
      - db

  # The PostgreSQL Database Service
  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=legal-tech
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
